name: Go
run-name: Working with GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [ '1.22' ]
    steps:
        - uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
        - name: Go Format
          run: gofmt -s -w . && git diff --exit-code
        - name: Go Vet
          run: go vet ./...
        - name: Go Tidy
          run: go mod tidy && git diff --exit-code
        - name: Go Mod
          run: go mod download
        - name: Go Mod Verify
          run: go mod verify
        - name: Install dependencies
          run: go get .
        - name: Build
          run: go build -v ./...
        - name: Test with the Go CLI
          run: go test
